import React from 'react'
import {KoiInfoTable} from '@/components/Layouts/koi-table'

const page = () => {
    const testData = [
        {
          picture_id: "koi_001.jpg",
          koi_id: "001",
          variety: "Kohaku",
          sex: "Male",
          age: "2",
          size_cm: "30",
          bre_id: "BR001",
          breeder: "Sakai Fish Farm",
          pcs: "1",
          jpy_cost: "50000",
          jpy_total: "50000",
          usd_cost: "450",
          usd_total: "450",
          sold_to: "John Doe",
          ship_to: "Los Angeles, USA",
          sales_jpy: "55000",
          comm_jpy: "5000",
          total_jpy: "60000",
          sales_usd: "500",
          comm_usd: "50",
          total_usd: "550",
          ship_date: "2025-03-15",
          num_of_box: "1",
          box_size: "Medium",
          kg: "10",
          total_kg: "10",
          shipped_yn: "Yes",
          grouping: "Single",
          sc_koi: "A",
        },
        {
          picture_id: "koi_002.jpg",
          koi_id: "002",
          variety: "Sanke",
          sex: "Female",
          age: "3",
          size_cm: "35",
          bre_id: "BR002",
          breeder: "Dainichi Koi Farm",
          pcs: "2",
          jpy_cost: "75000",
          jpy_total: "150000",
          usd_cost: "675",
          usd_total: "1350",
          sold_to: "Jane Smith",
          ship_to: "New York, USA",
          sales_jpy: "165000",
          comm_jpy: "15000",
          total_jpy: "180000",
          sales_usd: "1500",
          comm_usd: "150",
          total_usd: "1650",
          ship_date: "2025-03-18",
          num_of_box: "2",
          box_size: "Large",
          kg: "12",
          total_kg: "24",
          shipped_yn: "No",
          grouping: "Pair",
          sc_koi: "B",
        },,
        {
          picture_id: "koi_002.jpg",
          koi_id: "002",
          variety: "Sanke",
          sex: "Female",
          age: "3",
          size_cm: "35",
          bre_id: "BR002",
          breeder: "Dainichi Koi Farm",
          pcs: "2",
          jpy_cost: "75000",
          jpy_total: "150000",
          usd_cost: "675",
          usd_total: "1350",
          sold_to: "Jane Smith",
          ship_to: "New York, USA",
          sales_jpy: "165000",
          comm_jpy: "15000",
          total_jpy: "180000",
          sales_usd: "1500",
          comm_usd: "150",
          total_usd: "1650",
          ship_date: "2025-03-18",
          num_of_box: "2",
          box_size: "Large",
          kg: "12",
          total_kg: "24",
          shipped_yn: "No",
          grouping: "Pair",
          sc_koi: "B",
        },
        {
          picture_id: "koi_002.jpg",
          koi_id: "002",
          variety: "Sanke",
          sex: "Female",
          age: "3",
          size_cm: "35",
          bre_id: "BR002",
          breeder: "Dainichi Koi Farm",
          pcs: "2",
          jpy_cost: "75000",
          jpy_total: "150000",
          usd_cost: "675",
          usd_total: "1350",
          sold_to: "Jane Smith",
          ship_to: "New York, USA",
          sales_jpy: "165000",
          comm_jpy: "15000",
          total_jpy: "180000",
          sales_usd: "1500",
          comm_usd: "150",
          total_usd: "1650",
          ship_date: "2025-03-18",
          num_of_box: "2",
          box_size: "Large",
          kg: "12",
          total_kg: "24",
          shipped_yn: "No",
          grouping: "Pair",
          sc_koi: "B",
        },
        {
          picture_id: "koi_002.jpg",
          koi_id: "002",
          variety: "Sanke",
          sex: "Female",
          age: "3",
          size_cm: "35",
          bre_id: "BR002",
          breeder: "Dainichi Koi Farm",
          pcs: "2",
          jpy_cost: "75000",
          jpy_total: "150000",
          usd_cost: "675",
          usd_total: "1350",
          sold_to: "Jane Smith",
          ship_to: "New York, USA",
          sales_jpy: "165000",
          comm_jpy: "15000",
          total_jpy: "180000",
          sales_usd: "1500",
          comm_usd: "150",
          total_usd: "1650",
          ship_date: "2025-03-18",
          num_of_box: "2",
          box_size: "Large",
          kg: "12",
          total_kg: "24",
          shipped_yn: "No",
          grouping: "Pair",
          sc_koi: "B",
        },
        {
          picture_id: "koi_002.jpg",
          koi_id: "002",
          variety: "Sanke",
          sex: "Female",
          age: "3",
          size_cm: "35",
          bre_id: "BR002",
          breeder: "Dainichi Koi Farm",
          pcs: "2",
          jpy_cost: "75000",
          jpy_total: "150000",
          usd_cost: "675",
          usd_total: "1350",
          sold_to: "Jane Smith",
          ship_to: "New York, USA",
          sales_jpy: "165000",
          comm_jpy: "15000",
          total_jpy: "180000",
          sales_usd: "1500",
          comm_usd: "150",
          total_usd: "1650",
          ship_date: "2025-03-18",
          num_of_box: "2",
          box_size: "Large",
          kg: "12",
          total_kg: "24",
          shipped_yn: "No",
          grouping: "Pair",
          sc_koi: "B",
        }
      ];


  return (
    <div className="rounded-[10px] bg-white shadow-1 dark:bg-gray-dark dark:shadow-card p-8">
                <KoiInfoTable data={testData} />
            </div>
        )
  
}

export default page